language: objective-c
osx_image: xcode10
script:
  - xcodebuild -project EasyFutures.xcodeproj -scheme EasyFutures -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)